const CREATE_TILES = "CREATE_TILES";
const DESTROY_TILES = "DESTROY_TILES";
const UPDATE_TILE = "UPDATE_TILE";
const QUEUE_ANIMATION = "QUEUE_ANIMATION";
const ON_ALL_ANIMATION_END = "ON_ALL_ANIMATION_END";
const REFILL_BOARD = "REFILL_BOARD";
const CHANGE_SCENE = "CHANGE_SCENE";
const UPDATE_SCORE = "UPDATE_SCORE";
const TOGGLE_INTERACTIVITY = "TOGGLE_INTERACTIVITY";

export {
  CREATE_TILES,
  DESTROY_TILES,
  UPDATE_TILE,
  REFILL_BOARD,
  QUEUE_ANIMATION,
  ON_ALL_ANIMATION_END,
  UPDATE_SCORE,
  CHANGE_SCENE,
  TOGGLE_INTERACTIVITY
};
