const CREATE_TILES = "CREATE_TILES";
const DESTROY_TILES = "DESTROY_TILES";
const UPDATE_TILE = "UPDATE_TILE";

const REFILL_BOARD = "REFILL_BOARD";
const QUEUE_ANIMATION = "QUEUE_ANIMATION";
const CHANGE_SCENE = "CHANGE_SCENE";

export { CREATE_TILES, DESTROY_TILES, UPDATE_TILE, REFILL_BOARD, QUEUE_ANIMATION, CHANGE_SCENE };